#!/bin/sh

ESF_IPTABLES_CONFIG=/etc/sysconfig/iptables
TMP_IPTABLES_BACKUP=/tmp/esf-iptables-backup

sleep 2
mv $TMP_IPTABLES_BACKUP $ESF_IPTABLES_CONFIG
sed -i 's/-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER//g' $ESF_IPTABLES_CONFIG
sed -i 's/-A POSTROUTING -s 172\.18\.0\.4\/32 -d 172\.18\.0\.4\/32 -p udp -m udp --dport 1700 -j MASQUERADE//g' $ESF_IPTABLES_CONFIG
sed -i 's/-A POSTROUTING -s 172\.18\.0\.6\/32 -d 172\.18\.0\.6\/32 -p tcp -m tcp --dport 8080 -j MASQUERADE//g' $ESF_IPTABLES_CONFIG