- name: Install Bundle
  hosts: localhost
  connection: local

  roles:
    - eth-update

  tasks:
    - name: Check ESF version
      shell: eth_vers_esf
      register: esf_version

    - name: Backup ESF 6 dpa.properties
      copy:
        src: /opt/eurotech/esf/data/dpa.properties
        dest: /opt/eurotech/esf/data/dpa.properties.backup
      when: '"ESF_7." not in esf_version.stdout'
    - name: Backup ESF 6 Packages folder
      copy:
        src: /opt/eurotech/esf/data/packages
        dest: /opt/eurotech/esf/data/packages.backup
      when: '"ESF_7." not in esf_version.stdout'

    - name: Backup ESF 7 Packages folder
      copy:
        src: /opt/eurotech/esf/packages
        dest: /opt/eurotech/esf/packages.backup
      when: '"ESF_7." in esf_version.stdout'

    - name: Install DP
      block:
        - name: Install DP Https
          uri:
            url: https://127.0.0.1/services/deploy/v1/_install
            user: "maintenance"
            password: "maintenance12345"
            force_basic_auth: yes
            validate_certs: no
            method: POST
            body: "{\"url\": \"http://kura-repo.s3-us-west-2.amazonaws.com/ansible-tests/packages/org.eclipse.kura.demo.heater_1.0.500.dp\"}"
            body_format: json
          register: uri_data
      rescue:
        - name: Install DP Http
          uri:
            url: http://127.0.0.1/services/deploy/v1/_install
            user: "admin"
            password: "admin"
            force_basic_auth: yes
            validate_certs: no
            method: POST
            body: "{\"url\": \"http://kura-repo.s3-us-west-2.amazonaws.com/ansible-tests/packages/org.eclipse.kura.demo.heater_1.0.500.dp\"}"
            body_format: json
          register: uri_data
      ignore_errors: yes

    - name: Clean Backups
      block:
        - name: Delete ESF 6 dpa.properties backup
          file:
            path: /opt/eurotech/esf/data/dpa.properties.backup
            state: absent
        - name: Delete ESF 6 Packages backup
          file:
            path: /opt/eurotech/esf/data/packages.backup
            state: absent
        - name: Delete ESF 7 Packages backup
          file:
            path: /opt/eurotech/esf/packages.backup
            state: absent
      when: uri_data.status < 400

    - name: Restore Backups
      block:
        - name: Restore ESF 6 dpa.properties
          copy:
            src: /opt/eurotech/esf/data/dpa.properties.backup
            dest: /opt/eurotech/esf/data/dpa.properties
        - name: Restore ESF 6 Packages folder
          copy:
            src: /opt/eurotech/esf/data/packages.backup
            dest: /opt/eurotech/esf/data/packages
        - name: Restore ESF 7 Packages folder
          copy:
            src: /opt/eurotech/esf/packages.backup
            dest: /opt/eurotech/esf/packages
      when: uri_data.status >= 400

    - name: Restart esf
      shell: systemctl restart kura
      when: uri_data.status >= 400
