#PRE-ESF SETUP
- name: Pre-ESF Setup
  debug:
    msg: "Pre-ESF Setup"

# #Firewall Workaround Setup (EFS 6.2.0 only)
# - name: "EFS 6.2.0: Copy firewall workaround files (SKIP = EFS 7)"
#   copy: 
#     src: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: "{{ item.mode }}"
#   with_items:
#     - { src: firewall/addon-iptables, dest: /opt/firewall-docker-workaround/, mode: "0644" }
#     - { src: firewall/firewall_cust, dest: /etc/init.d/, mode: "0755" }
#     - { src: firewall/firewall_cust_aux, dest: /etc/init.d/, mode: "0755" }
#   when: esf_major_version != "7"



# MAKE SURE TO ENSURE FOLDERS EXIST BEFORE DOWNLOADING
# #Firewall Workaround Setup (EFS 6.2.0 only)
# - name: "EFS 6.2.0: Copy firewall workaround files (SKIP = EFS 7)"
#   get_url: 
#     url: "{{ item.src }}"
#     dest: "{{ item.dest }}"
#     mode: "{{ item.mode }}"
#     checksum: "md5:{{ item.checksum }}"
#   with_items:
#     - { src: "{{ aws_url }}/firewall/addon-iptables", dest: /opt/firewall-docker-workaround/, mode: "0644", checksum: "{{ addon_iptables_md5 }}"}
#     - { src: "{{ aws_url }}/firewall/firewall_cust", dest: /etc/init.d/, mode: "0755", checksum: "{{ firewall_cust_md5 }}" }
#     - { src: "{{ aws_url }}/firewall/firewall_cust_aux", dest: /etc/init.d/, mode: "0755", checksum: "{{ firewall_cust_aux_md5 }}" }
#   when: esf_major_version != "7"


#Create Docker network
- name: create docker network chirpbridge
  command: docker network create -d bridge --subnet 172.18.0.0/16 --gateway 172.18.0.1 --opt com.docker.network.bridge.name=chirpbridge chirpbridge