- name: EL 40 OTA upgrade and ESF migration
  hosts: localhost
  connection: local
  gather_facts: True

  roles:
    - eth-update

  tasks:   
    - name: Download ota package
      get_url:
        url: https://kura-repo.s3.us-west-2.amazonaws.com/ansible-tests/ACTIVITIES-V1/ota.tar.gz
        dest: /tmp/ota.tar.gz
        mode: 0440

    - name: Unpack ota package
      unarchive:
        src: /tmp/ota.tar.gz
        dest: /var/lib/docker
        remote_src: True

    - name: Remove ota compressed package
      file:
        path: /tmp/ota.tar.gz
        state: absent

    - name: Run OTA Upgrader
      shell: /var/lib/docker/ota/go

    - name: schedule device reboot in one minute
      shell: shutdown -r 1