#Chirpstack Setup
- name: Reset Environment
  debug:
    msg: "Reset Environment"

- name: start docker
  systemd:
    name: docker
    state: started
    #enabled: yes #this doesn't work due to bug

#Enable Docker
- name: enable docker start-at-boot
  become: yes
  shell: systemctl reenable docker

##Remove existing docker containers and volumes. Remove chirpstack network
- name: stop all docker containers
  command: "docker stop {{ item }}"
  register: docker_result
  loop: "{{ docker_image_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("requires at least 1 argument")

- name: remove all docker containers
  command: "docker rm {{ item }}"
  loop: "{{ docker_image_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("requires at least 1 argument")

- name: remove all docker volumes
  command: "docker volume rm {{ item }}"
  loop: "{{ docker_volume_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("requires at least 1 argument")

- name: remove chirpstack docker network
  command: docker network rm chirpbridge
  failed_when:
    - docker_result.stderr != ""
    - docker_result.stderr is not search("no such network")