#Chirpstack Setup
- name: Reset Environment
  debug:
    msg: "Reset Environment"

- name: start docker
  systemd:
    name: docker
    state: restarted
    #enabled: yes #this doesn't work due to bug, see workaround in next task

#Enable Docker Workaround
#Service must be disabled then enabled. Simply enabling may not persist over reboot due to Ansible bug. 
#This command works for all modern systemd services. This will NOT work for old system V services that are wrapped. 
#For those older services, you must do two separate commands to first disable, then enable. 
- name: enable docker start-at-boot
  become: yes
  shell: systemctl reenable docker

##Remove docker assets from previous install (if any)
- name: stop all docker chirpstack containers
  command: "docker stop {{ item }}"
  register: docker_result
  loop: "{{ docker_image_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such container:")
  changed_when: docker_result.stderr is not search("No such container:")

- name: remove all docker chirpstack containers
  command: "docker rm {{ item }}"
  register: docker_result
  loop: "{{ docker_image_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such container:")
  changed_when: docker_result.stderr is not search("No such container:")

- name: remove all docker chirpstack volumes
  command: "docker volume rm {{ item }}"
  register: docker_result
  loop: "{{ docker_volume_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such volume:")
  changed_when: docker_result.stderr is not search("No such volume:")

- name: remove docker chirpstack network
  command: docker network rm chirpbridge
  register: docker_result
  failed_when:
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such network:")
  changed_when: docker_result.stderr is not search("No such network:")
