#Chirpstack Setup
- name: Reset Environment
  debug:
    msg: "Reset Environment"

- name: start docker
  systemd:
    name: docker
    state: started
    #enabled: yes #this doesn't work due to bug

#Enable Docker
- name: enable docker start-at-boot
  become: yes
  shell: systemctl reenable docker

##Remove existing docker containers and volumes. Remove chirpstack network
- name: stop all docker containers
  command: "docker stop {{ item }}"
  register: docker_result
  with_items:
    - redis-chirpstack
    - postgres-chirpstack
    - chirpstack-application-server
    - chirpstack-network-server
    - chirpstack-gateway-bridge
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("requires at least 1 argument")

- name: remove all docker containers
  shell: docker rm $(docker ps -a -q)
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("requires at least 1 argument")

- name: remove all docker volumes
  shell: docker volume rm $(docker volume ls -q)
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("requires at least 1 argument")

- name: remove chirpstack docker network
  shell: docker network rm chirpbridge
  failed_when:
    - docker_result.stderr != ""
    - docker_result.stderr is not search("no such network")