#Chirpstack Setup
- name: Reset Environment
  debug:
    msg: "Reset Environment"

- name: start docker
  systemd:
    name: docker
    state: restarted
    #enabled: yes #this doesn't work due to bug

#Enable Docker
- name: enable docker start-at-boot
  become: yes
  shell: systemctl reenable docker

##Remove existing docker chirpstack containers and volumes. Remove chirpstack network
- name: stop all docker chirpstack containers
  command: "docker stop {{ item }}"
  register: docker_result
  loop: "{{ docker_image_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such container:")
  changed_when: docker_result.stderr is not search("No such container:")

- name: remove all docker chirpstack containers
  command: "docker rm {{ item }}"
  register: docker_result
  loop: "{{ docker_image_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such container:")
  changed_when: docker_result.stderr is not search("No such container:")

- name: remove all docker chirpstack volumes
  command: "docker volume rm {{ item }}"
  register: docker_result
  loop: "{{ docker_volume_names }}"
  failed_when: 
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such volume:")
  changed_when: docker_result.stderr is not search("No such volume:")

- name: remove docker chirpstack network
  command: docker network rm chirpbridge
  register: docker_result
  failed_when:
    - docker_result.stderr != ""
    - docker_result.stderr is not search("No such network:")
  changed_when: docker_result.stderr is not search("No such network:")
