- name: ESF upgrade
  hosts: localhost
  connection: local
  gather_facts: True

  roles:
    - eth-update

  tasks:
    - name: Download rpm
      get_url:
        url: https://www.eurotech.com/download/en/download.aspx?url=/PrdEth/ESF%207.0.X/System%20Distribution/esf-reliagate-10-12-el27-7.0.1-1.cortexa8hf_neon.rpm
        dest: /tmp/updated.rpm
        mode: 0777
    
    - name: Upgrade via DNF
      shell: "dnf upgrade -y /tmp/updated.rpm"
    
    - name: Schedule device reboot in one minute
      shell: shutdown -r 1