- name: Install TE Demo Kit
  hosts: localhost
  connection: local

  vars:
    gw_1012: "ReliaGATE 10-12"
    gw_1014: "ReliaGATE 10-14"
    docker_image_names:
      - redis-chirpstack
      - postgres-chirpstack
      - chirpstack-application-server
      - chirpstack-network-server
      - chirpstack-gateway-bridge
    docker_volume_names:
      - redis-data-chirpstack
      - postgres-data-chirpstack
    esf_username: "admin"
    #EFS version specific variables
    #These variables are set to a default of EFS 6.2.0. 
    #If EFS 7 is in use, they will be changed (in the validate_environment role)
    esf_api_http_protocol: "http" #EFS 6.2.0: http; EFS 7: https
    esf_password: "admin" #EFS 6.2.0: "admin"; EFS 7: serial number

  #pre_tasks:

  roles:
    - validate_environment
    - reset_environment
    #- pre_esf_linux_setup
    #- esf_setup
    #- post_esf_linux_setup
    #- chirpstack_install
    #- chirpstack_configure

  post_tasks:
       
#    - name: Reboot gateway
#      shell: /sbin/reboot
#      when: reboot