- name: Install TE Demo Kit
  hosts: localhost
  connection: local

  vars:
    gw_1012: "ReliaGATE 10-12"
    gw_1014: "ReliaGATE 10-14"
    esf_username: "admin"
    esf_password: "admin"
    docker_image_names:
      - redis-chirpstack
      - postgres-chirpstack
      - chirpstack-application-server
      - chirpstack-network-server
      - chirpstack-gateway-bridge
    docker_volume_names:
      - redis-data-chirpstack
      - postgres-data-chirpstack

  pre_tasks:

  roles:
    - validate_environment
    - reset_environment
    #- pre_esf_linux_setup
    #- esf_setup
    #- post_esf_linux_setup
    #- chirpstack_install
    #- chirpstack_configure

  post_tasks:
       
#    - name: Reboot gateway
#      shell: /sbin/reboot
#      when: reboot