- name: Install LoRa All-In-One Gateway Software
  hosts: localhost
  connection: local

  vars:
    #List of OTAA Sensors
    #This is is the list that is used in the chirpstack_configure role 
    #This functionality is commented by default. See details in the chirpstack_configure role to enable it
    #otaa_sensor_list:
    #  - { name: 'example_te_8911_1' , description: 'Example TE 8911 Sensor #1', devEUI: 'ABCDEF123AAAABBB', appKEY: 'ABCDEFABCDEFABCDEF123AAAAABBBBBC' }
    #  - { name: 'example_te_8911_2' , description: 'Example TE 8911 Sensor #2', devEUI: '321FEDCBABBBBAAA', appKEY: 'FEDCBAFEDCBAFEDCBA123BBBBBAAAAAC' } 

    gw_1012: "ReliaGATE 10-12"
    gw_1014: "ReliaGATE 10-14"
    docker_image_names:
      - redis-chirpstack
      - postgres-chirpstack
      - chirpstack-application-server
      - chirpstack-network-server
      - chirpstack-gateway-bridge
    docker_volume_names:
      - redis-data-chirpstack
      - postgres-data-chirpstack
    esf_username: "admin"
    
    #EFS version specific variables
    #These variables are set to the default values for EFS 6.2.0. 
    #If EFS 7 is in use, they will be changed in the validate_environment role
    esf_api_http_protocol: "http" #EFS 6.2.0: http; EFS 7: https
    esf_password: "admin" #EFS 6.2.0: "admin"; EFS 7: serial number

    #Hardware specific variables
    #These variables are set by default to the ReliaGATE 10-14. 
    #If other hardware is in use, they will be changed in the validate_environment role
    image_arch: "arm64v8"
    
    #AWS file storage base address (does NOT include trailing slash)
    aws_url: "http://eth-inc-sw.s3.amazonaws.com/lora/ansible-lora-install-support-files"

    #MD5's of files to download
    addon_iptables_md5: "c0e7819c458f5ba39fb82601060bafbb"
    firewall_cust_md5: "d3f332b02ed14b72d1b211bddd3fceab"
    firewall_cust_aux_md5: "da8f14cc2bf3ce9691c9d41b8908d25f"
    postgres_init_1_md5: "52d9b10a4d6323e1327a23c8577854ed"
    postgres_init_2_md5: "24d4adb3052298d9c338350a38eb738a"
    postgres_init_3_md5: "55a43197cdb8fa034d577c77feb5669f"
    postgres_init_4_md5: "7902d43d6171fb91b347a13042beee61"
    global_conf_md5: "20e34722d62da60474cab1d02c9123eb"
    local_conf_md5: "d9762eda1a1403642e8df4b168dfa4d3"
    cas_config_md5: "819af396274a49b52e748352b4127438"
    cns_config_md5: "03d1f593f434cc47b57c0a7e056b9279"
    cgb_config_md5: "d436ceb9fcf745e4a7e70bc76b3d6f9c"
    docker_daemon_json_md5: "a6ba49cf41e8782fbe035a9a28e8fe69"
    lora_installer_version_md5: "c46d926976e79a805b0e8111d7915c2c"

  roles:
    - validate_environment
    - reset_environment
    - pre_esf_linux_setup
    - esf_setup
    - post_esf_linux_setup
    - chirpstack_install
    - chirpstack_configure