- name: Update GPG Key
  hosts: localhost
  connection: local

  tasks:
    - name: Copy gpgpub key
      copy:
        src: 'gpgpub.key'
        dest: '/tmp'
        mode: '0644'

    - name: Install the GPG public key
      command: rpm --import /tmp/gpgpub.key
      args:
        warn: false